python lerobot/lerobot/scripts/train.py \
  --policy.type=smolvla \
  --dataset.repo_id=aopolin-lv/libero_spatial_no_noops_lerobot_v21 \
  --batch_size=64 \
  --steps=100000 \
  --policy.device=cuda \
  --wandb.enable=true \
  --save_freq 50000 \
  --output_dir=/po2/heimrih/lerobot/libero_smolvla \
  --policy.push_to_hub=false \
  --wandb.project=libero_smolvla \
  --job_name=libero_smolvla
